city_map = {
    "london": "London",
    "birmingham": "Birmingham",
    "manchester": "Manchester",
    "glasgow": "Glasgow",
    "leeds": "Leeds",
    "liverpool": "Liverpool",
    "newcastle upon tyne": "Newcastle upon Tyne",
    "sheffield": "Sheffield",
    "bristol": "Bristol",
    "edinburgh": "Edinburgh",
    "leicester": "Leicester",
    "coventry": "Coventry",
    "nottingham": "Nottingham",
    "kingston upon hull": "Kingston upon Hull",
    "stoke-on-trent": "Stoke-on-Trent",
    "southampton": "Southampton",
    "reading": "Reading",
    "cardiff": "Cardiff",
    "belfast": "Belfast",
    "derby": "Derby",
    "plymouth": "Plymouth",
    "wolverhampton": "Wolverhampton",
    "luton": "Luton",
    "warrington": "Warrington",
    "swansea": "Swansea",
    "southend-on-sea": "Southend-on-Sea",
    "aberdeen": "Aberdeen",
    "oxford": "Oxford",
    "poole": "Poole",
    "cambridge": "Cambridge",
    "york": "York",
    "peterborough": "Peterborough",
    "dundee": "Dundee",
    "stockport": "Stockport",
    "ipswich": "Ipswich",
    "middlesbrough": "Middlesbrough",
    "bolton": "Bolton",
    "blackpool": "Blackpool",
    "telford": "Telford",
    "west bromwich": "West Bromwich",
    "brighton and hove": "Brighton and Hove",
    "slough": "Slough",
    "gloucester": "Gloucester",
    "exeter": "Exeter",
    "watford": "Watford",
    "rotherham": "Rotherham",
    "newport": "Newport",
    "basingstoke": "Basingstoke",
    "eastbourne": "Eastbourne",
    "preston": "Preston",
    "cheltenham": "Cheltenham",
    "lincoln": "Lincoln",
    "chester": "Chester",
    "chelmsford": "Chelmsford",
    "huddersfield": "Huddersfield",
    "basildon": "Basildon",
    "sunderland": "Sunderland",
    "bournemouth": "Bournemouth",
    "swindon": "Swindon",
    "milton keynes": "Milton Keynes",
    "colchester": "Colchester",
    "derry": "Derry",
    "st albans": "St Albans",
    "solihull": "Solihull",
    "hastings": "Hastings",
    "woking": "Woking",
    "gillingham": "Gillingham",
    "worcester": "Worcester",
    "rochdale": "Rochdale",
    "birkenhead": "Birkenhead",
    "bury": "Bury",
    "barnsley": "Barnsley",
    "maidstone": "Maidstone",
    "crawley": "Crawley",
    "doncaster": "Doncaster",
    "norwich": "Norwich",
    "bedford": "Bedford",
    "brentwood": "Brentwood",
    "folkestone": "Folkestone",
    "worthing": "Worthing",
    "bath": "Bath",
    "darlington": "Darlington",
    "inverness": "Inverness",
    "burnley": "Burnley",
    "welwyn garden city": "Welwyn Garden City"
}